export const text = {
  firstName: "Имя",
  secondName: "Фамилия",
  fatherName: "Отчество",
  birthday: "Дата рождения",
  male: "Мальчик",
  address: "Адрес",
  phoneNumber: "Контактный телефон",
  phoneNumber2: "Контактный телефон",
  firstVaccination: "Первая прививка",
  approveFirstVaccination: "Первая прививка разрешена",
  secondVaccination: "Вторая прививка",
  approveSecondVaccination: "Вторая прививка разрешена",
  thirdVaccination: "Третья прививка",
  approveThirdVaccination: "Третья прививка разрешена",
  fourthVaccination: "Четвёртая прививка",
  approveFourthVaccination: "Четвёртая прививка разрешена",
};

export const placeholderText = {
  firstName: "Введите имя",
  secondName: "Введите фамилию",
  fatherName: "Введите отчество",
  birthday: "Укажите дату рождения",
  male: "Пол мальчик",
  address: "Введите адрес",
  phoneNumber: "Введите контактный телефон",
  phoneNumber2: "Введите контактный телефон",
  firstVaccination: "Первая прививка проведена",
  approveFirstVaccination: "Первая прививка разрешена",
  secondVaccination: "Вторая прививка проведена",
  approveSecondVaccination: "Вторая прививка разрешена",
  thirdVaccination: "Третья прививка проведена",
  approveThirdVaccination: "Третья прививка разрешена",
  fourthVaccination: "Четвёртая прививка проведена",
  approveFourthVaccination: "Четвёртая прививка разрешена",
};
